<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AppendTargetFrameworkToOutputPath>output</AppendTargetFrameworkToOutputPath>
        <OutputPath>$(LocalAppData)\Kitopia\plugins\kitopiaonnxruntimeopenvino\</OutputPath>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Intel.ML.OnnxRuntime.OpenVino" Version="1.23.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PluginCore\PluginCore.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <None Update="manifest.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
