<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Intel.ML.OnnxRuntime.OpenVino" Version="1.20.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PluginCore\PluginCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="manifest.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
