<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <AssemblyName>KitopiaEx</AssemblyName>
        <RootNamespace>KitopiaEx</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AppendTargetFrameworkToOutputPath>output</AppendTargetFrameworkToOutputPath>
        <OutputPath>$(LocalAppData)\Kitopia\plugins\kitopiaex\</OutputPath>

    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>none</DebugType>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PluginCore\PluginCore.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </ProjectReference>

    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="SharpHook" Version="7.1.1" />
    </ItemGroup>


    <ItemGroup>
        <None Update="manifest.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Ocr\ocr_det.onnx">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Ocr\ocr_rec.onnx">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Ocr\rec_word_dict.txt">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
