<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(OS)' != 'Windows_NT' ">
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <WindowsPackageType>None</WindowsPackageType>
        <EnableMsixTooling>true</EnableMsixTooling>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.28.0" />
        <PackageReference Include="PDFsharp" Version="6.2.4" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Kitopia.Desktop.Platform.Windows\Kitopia.Desktop.Platform.Windows.csproj" />
      <ProjectReference Include="..\Kitopia.Desktop.Features\Kitopia.Desktop.Features.csproj" />
      <ProjectReference Include="..\Kitopia.Desktop\Kitopia.Desktop.csproj" />
    </ItemGroup>

</Project>
