<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup Condition=" '$(OS)' != 'Windows_NT' ">
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <WindowsPackageType>None</WindowsPackageType>
        <EnableMsixTooling>true</EnableMsixTooling>
    </PropertyGroup>
    <PropertyGroup>
       
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))'">
        <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))'">
        <DefineConstants>$(DefineConstants);OSX</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.2.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Kitopia.Desktop.Platform.Windows\Kitopia.Desktop.Platform.Windows.csproj" />
      <ProjectReference Include="..\Kitopia.Desktop.Platform.Linux\Kitopia.Desktop.Platform.Linux.csproj" />
      <ProjectReference Include="..\Kitopia.Desktop.Features\Kitopia.Desktop.Features.csproj" />
      <ProjectReference Include="..\Kitopia.Desktop\Kitopia.Desktop.csproj" />
      <ProjectReference Include="..\Kitopia.Feature\Kitopia.Feature.csproj" />
      <ProjectReference Include="..\Kitopia.Feature.Avalonia\Kitopia.Feature.Avalonia.csproj" />
      <ProjectReference Include="..\Mobile\Kitopia.Mobile\Kitopia.Mobile.csproj" />
    </ItemGroup>

</Project>
