<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-ios26.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Kitopia.Mobile</RootNamespace>
        <AssemblyName>Kitopia.Mobile.iOS</AssemblyName>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Kitopia.Mobile\Kitopia.Mobile.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.iOS" Version="12.0.5" />
    </ItemGroup>
</Project>
