<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AppendTargetFrameworkToOutputPath>output</AppendTargetFrameworkToOutputPath>
        <OutputPath>$(LocalAppData)\Kitopia\plugins\kitopiaonnxruntimegpu\</OutputPath>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PluginCore\PluginCore.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <None Update="manifest.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Windows" Version="1.22.0" />
    </ItemGroup>

</Project>
