<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\KitopiaVersion.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Kitopia.Desktop.Abstractions\Kitopia.Desktop.Abstractions.csproj"/>
        <ProjectReference Include="..\Kitopia.Desktop.Features\Kitopia.Desktop.Features.csproj"/>
        <ProjectReference Include="..\Kitopia.Desktop.PluginSdk\Kitopia.Desktop.PluginSdk.csproj"/>
    </ItemGroup>

</Project>
